### PR TITLE
Fix inspection warnings

### PR DESCRIPTION
**Pull request by mkurdej**
Warnings from http://boost.cowic.de/rc/docs-inspect-develop.html#units

### CODE REVIEW

**Comment by jhunold** [comment]
Looks fine. But the patch mixes whitespace changes with the actual warning fixes which makes it hard to find the relevant changes in the diff. Can you split this into two commits, one fixing whitespace and another one for the warnings?

**Comment by mkurdej** [comment]
Splitted into 2 commits. Is it ok now?

**Comment by mkurdej** [comment]
Ping?

**Comment by jhunold** [comment]
Sorry for the delay.

**Pull request merged**
