### PR TITLE
Changes for Embarcadero C++ clang-based compilers, targeting Boost 1.74

### PR DESCRIPTION
**Pull request by eldiener**

### CODE REVIEW

**Comment by eldiener** [comment]
Some coverity scan test failed with:

```
The command "echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-" exited with 0.

0.21s$ libs/$SELF/covscan.sh

+pushd /tmp

/tmp ~/build/boostorg/boost-root

+rm -rf coverity_tool.tgz 'cov-analysis*'

+wget -nv https://scan.coverity.com/download/linux64 --post-data 'token=&project=boostorg/units' -O coverity_tool.tgz

Username/Password Authentication Failed.

The command "libs/$SELF/covscan.sh" exited with 6.
cache.2

store build cache
```
This has nothing to do with this PR. Can this please be merged ?

**Comment by eldiener** [comment]
Steven,

Is there any reason you do not want to merge this PR  ? It has been 3 months since submitting this simple PR and I do not understand why it has not been merged to develop. If it does not get into the 1.74 release that is not significant , but the reason that you have not merged the PR  eludes me.

**Comment by pdimov** [comment]
I don't like the `bu::information::byte` changes. First, you should use a using declaration instead of qualifying everything. Second, there should be a comment explaining why it's needed (where does a global `byte` come from?). Third, it should probably be ifdef-ed for the specific compiler needing it.

**Comment by eldiener** [comment]
The mnemonic 'byte' is too common to be unqualified. It occurs in certain Windows header files and we all know there are no namespaces there nor has Microsoft ever cared about common mnemonic names themselves, so it is not a compiler issue other than that certain compilers include certain Windows header files while others do not. I do not understand why a 'using' declaration solves the problem. Do you mean as a way of typedefing the type and then using that name instead ? I really think that not hiding behind a typedef is better, but if you insist I can do that.

**Comment by pdimov** [comment]
I mean add `using bu::information::byte;`

**Comment by eldiener** [comment]
How does adding `using bu::information::byte;` solve the problem when `byte` is also an unjqualified type in a Windows header file ?

**Comment by pdimov** [comment]
Did you try it? Immediately after `using namespace bu::information;`.

**Comment by eldiener** [comment]
Peter: Thanks for tolerating my stupidity and helping out getting the Embarcadero C++ clang-based changes merged for the remaining libaries.

**Comment by pdimov** [comment]
No problem. :-)

**Pull request merged**
